name: Publish Docker images

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        versions: [6]
    env:
      repo: "govpf/spa-base" # Please don't forget to create the repo on Docker Hub
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Login to DockerHub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6.1.0
      with:
        context: ./apache
#        context: ./${{ matrix.versions }}
        file: ./apache/Dockerfile
#        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:apache
#          ${{ env.repo }}:${{ matrix.versions }}

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
